### ISSUE TITLE
React TypeScript compiler

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit.envs#59]
I have a project written in react and typescript, and the compiler is not working.
Only if I go back and install compiler version 3.0.1 is working, this version is the last before updating the compiler to work with the typescript base compiler and with the capsule.

STR:
- clone this project https://github.com/JoshK2/create-react-components-library.
- run this bit add command: `bit add src/assets/* -n assets && bit add src/components/*/ -t 'src/components/{PARENT}/*test.tsx' && bit add src/styles/* -n styles && bit add src/utils/*/ -t 'src/utils/{PARENT}/*test.ts'`
- run bit status, should be ok.
- run bit build to see the error.

This is the compiler I used and it's working: https://bit.dev/bit/envs/compilers/react-typescript/~dependencies?version=3.0.1

This is the compiler I used and it's NOT working: https://bit.dev/bit/envs/compilers/react-typescript/~dependencies?version=3.0.21

**Comment by qballer** [comment]
Hi @JoshK2 there are several issues here: 

1. configuration, i've used the following. 
Changes: 
* When there is no typescript file `tsc` will fail because he thinks you miss configured it. I've removed those components compiler (assests/styles). 
** @types/jest is global and can't be inferred from the code so it must be added.
```javascript
  "bit": {
    "overrides": {
      "*": {
        "devDependencies": {
          "@types/jest":"+"
        }
      },
      "assests/*": {
        "env": {
          "compiler": "-"
        }
      },
      "styles/*": {
        "env": {
          "compiler": "-"
        }
      }
    },
    "env": {
      "compiler": "bit.envs/compilers/typescript@3.0.26"
    },
    "componentsDefaultDirectory": "components/{name}",
    "packageManager": "npm"
  }
```
2. Bit doesn't recognise the `@types/react` devDependency. 
3. No proper error is seen by the user - this I'm going to fix in the compiler. 

This is less then an optimal experience.

**Comment by GiladShoham** [comment]
the @types resolved - see 
https://github.com/teambit/bit/issues/1990
part of dev.5

**Comment by qballer** [comment]
You can also now get errors to the console from typescript. 
Asset only components are supported
